server:
  port: 8001
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.cloud.pojo

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: #修改默认描述信息
    instance-id: springcloud-provider-dept-8001-Hystric
info:
  app.name: com.springcloud
  company.name: springboot.actuator

