server:
  port: 9527


spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: #修改默认描述信息
    instance-id: springcloud-zuul-9527
    prefer-ip-address: true


info:
  app.name: com.springcloud
  company.name: springboot.zuul
zuul:
  routes:
     mydept.serviceId: springcloud-provider-dept
     mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept #springcloud-provider-dept这个路径不能再进行访问了
